### ISSUE TITLE
Kompatibilität Contao 4.11

### ISSUE THREAD

**Issue by operatorone** [inspiredminds/contao-include-info#3]
Da ich diese Erweiterung sehr schätze und per Standard immer mit installiere, wollte ich gerne wissen, ob diese schon kompatibel zu Contao 4.11 ist.

**Comment by fritzmg** [comment]
Mir wären zumindest keine Probleme bekannt. Zu beachten ist nur, dass zur Installation ggf. eine vollständige Paketaktualisierung notwendig ist, da aktuell noch ein Symfony Downgrade erforderlich ist. Einfach ausprobieren und dann berichten ;)

**Comment by operatorone** [comment]
Moin, danke für deinen Tipp. Hat geklappt. Lag an dem Symfony Downgrade. Hätte das eigentlich irgendwelche Folgen für die Funktion von Contao 4.11 bezüglich Symfony?

**Comment by fritzmg** [comment]
Nein, sollte keine negativen Auswirkungen haben (außer deine Applikationsanpassungen verlassen sich auf die höhere Symfony Version).

**Comment by fritzmg** [comment]
Habe jetzt Version 1.0.2 veröffentlicht, wo auch Symfony 5 freigeschalten ist. Soweit getestet gibt es damit keine Probleme.
