### ISSUE TITLE
Update auf Version 2.0.0

### ISSUE THREAD

**Issue by pressi** [inspiredminds/contao-include-info#6]
Hallo,

das Update von Version 1.2.6 auf 2.0.0 in einer Contao 5.0.5 Installation schlägt fehl.

`PHP Fatal error:  Declaration of InspiredMinds\IncludeInfoBundle\IncludeInfoBundle::getContainerExtension() must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension(): ?Symfony\Component\DependencyInjection\Extension\ExtensionInterface in /vendor/inspiredminds/contao-include-info/src/IncludeInfoBundle.php on line 20`

LG pressi

**Comment by fritzmg** [comment]
Should be fixed in `2.0.1` now.
