### ISSUE TITLE
1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by Samson1964** [inspiredminds/contao-include-info#7]
Bei der Ausführung von
`
CREATE INDEX tag_params ON tl_inserttag_index (tag, params)
`
kommt der o.g. Fehler. tag und params sind varchar(255). Bei UTF8 also jeweils 510 Bytes, zusammen 1020.

**Comment by fritzmg** [comment]
You either need to switch to `InnoDB` with `utf8mb4` - or update to version `2.0.5` of the extension.
