### ISSUE TITLE
Layoutfehler in C5.3

### ISSUE THREAD

**Issue by zonky2** [inspiredminds/contao-include-info#8]
In C5.3.17 sieht die Listenansicht bei mir so aus:
![image_2024_11_25T10_43_38_230Z](https://github.com/user-attachments/assets/05f90c22-4bd5-4063-897c-d187683a9b53)

**Comment by fritzmg** [comment]
Fixed in `2.0.4  👍

**Comment by zonky2** [comment]
Danke!
:heart:
